name: publish_changes
run-name: Build template file and publish as release
on:
  push:
    branches:
      - 'master'
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Copy template file and print commit
        run: |
          ls $RUNNER_WORKSPACE
          echo $GITHUB_WORKFLOW_SHA
      - name: run shell script to build template files
        run: |
          chmod 770 ${GITHUB_WORKSPACE}/build/build_templates.sh
          ${GITHUB_WORKSPACE}/build/build_templates.sh ${GITHUB_WORKSPACE}/R/plots $RUNNER_WORKSPACE
          more $RUNNER_WORKSPACE/R_plots_templates.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ runner.workspace }}/figure-templates.txt"
          commit: master
          tag: "test_tag"
      
