name: publish_changes
run-name: Build template file and publish as release
on:
  push:
    branches:
      - 'master'
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Copy template file and print commit
        run: |
          cp knime-scripting-templates/R/figure-templates.txt $RUNNER_WORKSPACE
          ls $RUNNER_WORKSPACE
          echo $GITHUB_WORKFLOW_SHA
      - name: run shell script to build template files
        run: |
          chmod 770 knime-scripting-templates/build/build_templates.sh
          knime-scripting-templates/build/build_templates.sh knime-scripting-templates/R/plots $RUNNER_WORKSPACE
          ls -l $RUNNER_WORKSPACE
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ runner.workspace }}/figure-templates.txt"
          commit: master
          tag: "test_tag"
      
