name: publish_changes
run-name: Build template file and publish as release
on:
  push:
    branches:
      - 'master'
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Copy template file
        run: cp knime-scripting-templates/R/figure-templates.txt $RUNNER_HOME
      - name: confirm
        run: ls $RUNNER_HOME
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
