name: publish_changes
run-name: Build template file and publish as release
on:
  push:
    branches:
      - 'master'
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: set environment variables
        run: |
          echo "ASSETS_DIR=$RUNNER_WORKSPACE/assets" >> $GITHUB_ENV
          echo "DATETIME=v$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV
      - name: show all environment variables for this workflow
        run: env
      - name: create asset directory
        run: mkdir $ASSETS_DIR
      - name: run shell script to build template files
        run: |
          chmod 770 ${GITHUB_WORKSPACE}/build/build_templates.sh
          ${GITHUB_WORKSPACE}/build/build_templates.sh ${GITHUB_WORKSPACE}/R/plots $ASSETS_DIR
          more $ASSETS_DIR/R_plots_templates.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.ASSETS_DIR }}/*"
          commit: master
          tag: "${{ env.DATETIME }}"
          makeLatest: true
      
